services:
  - type: web
    name: amy-wightman-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20